### ISSUE TITLE
How do we reset or reload the captcha in this case.

### ISSUE THREAD

**Issue by Kanav** [rajan-g/angular2-google-recaptcha#6]

**Comment by rajan-g** [comment]
simple using *ngIf flag you can reset

**Comment by Kanav** [comment]
Hi @rajan-g . Can you share an example. The way my application works is that when i load the component where recaptcha is added , it is presented in a modal and when i interact with the recaptcha saying i'm not a robot the next time when i open the modal the recaptcha shows with the green tick without any interaction.

**Comment by rajan-g** [comment]
While you are opening modal you can reset your modal container or recaptcha container like below 

<div *ngIf="enableCaptcha">
here place your recaptcha code
</div>

in your control, while you are open modal you can set
 enableCaptcha = false; 
 setTimeout(()=> enableCaptcha=true,10);
